version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - ./config/db.env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./config/backend.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80" 
