version: "3.8"

services:
  backend:
      build: ./backend
      ports:
        - "8000:8000"
      volumes:
        - ./backend/src:/app
      env_file:
        - config/backend.env
      depends_on:
        - db
      command: >
        sh -c "python src/init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    env_file:
      - config/db.env
